/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaleDevicesRouteImport } from './routes/stale-devices'
import { Route as SyncsRouteImport } from './routes/syncs'
import { Route as TrendRouteImport } from './routes/trend'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaleDevicesRoute = StaleDevicesRouteImport.update({
  id: '/stale-devices',
  path: '/stale-devices',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncsRoute = SyncsRouteImport.update({
  id: '/syncs',
  path: '/syncs',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendRoute = TrendRouteImport.update({
  id: '/trend',
  path: '/trend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stale-devices': typeof StaleDevicesRoute
  '/syncs': typeof SyncsRoute
  '/trend': typeof TrendRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stale-devices': typeof StaleDevicesRoute
  '/syncs': typeof SyncsRoute
  '/trend': typeof TrendRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stale-devices': typeof StaleDevicesRoute
  '/syncs': typeof SyncsRoute
  '/trend': typeof TrendRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/stale-devices' | '/syncs' | '/trend' | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/stale-devices' | '/syncs' | '/trend' | '/api/trpc/$'
  id: '__root__' | '/' | '/stale-devices' | '/syncs' | '/trend' | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StaleDevicesRoute: typeof StaleDevicesRoute
  SyncsRoute: typeof SyncsRoute
  TrendRoute: typeof TrendRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stale-devices': {
      id: '/stale-devices'
      path: '/stale-devices'
      fullPath: '/stale-devices'
      preLoaderRoute: typeof StaleDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syncs': {
      id: '/syncs'
      path: '/syncs'
      fullPath: '/syncs'
      preLoaderRoute: typeof SyncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trend': {
      id: '/trend'
      path: '/trend'
      fullPath: '/trend'
      preLoaderRoute: typeof TrendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StaleDevicesRoute: StaleDevicesRoute,
  SyncsRoute: SyncsRoute,
  TrendRoute: TrendRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
